### ISSUE TITLE
[kiel] : Support HasStableId in adapterOf

### ISSUE THREAD

**Issue by ibrahimyilmaz** [ibrahimyilmaz/kiel#28]
In order to set hasStableId, we may pass lambda or interface to RecyclerViewAdapter to override getItemId. 

When it is passed,  `RecyclerViewAdapter` use it,
When it is not passed, `RecyclerViewAdapter` default `super.getItemId()`

Aim is to make it composable also:

syntax would be:

```kt
val adapter =adapterOf<Type>{
         itemId{ t.getId() }
         ....
}

```

**Comment by cyb3rko** [comment]
Was it ever included? Because I couldn't find a way to use it.

**Comment by ibrahimyilmaz** [comment]
Hi there, It is not included. But we can do it if you wanna have it.

**Comment by cyb3rko** [comment]
Would be nice to have. :)
Tell me if I can help you with that.

**Comment by ibrahimyilmaz** [comment]
You are always welcome to contribute the with PR

**Comment by cyb3rko** [comment]
I think for that my knowledge is not good enough :(
