### ISSUE TITLE
[kiel] Create alternative methods for register , where layoutResource is passed as a value, and then wrapped into a function type.

### ISSUE THREAD

**Issue by ibrahimyilmaz** [ibrahimyilmaz/kiel#33]
Create alternative methods for register , where layoutResource is passed as a value, and then wrapped into a function type.

This
```
register(
    type = Text::class.java
    layoutResource = { R.layout.adapter_message_text_item }
    viewHolder = { ::TextMessageViewHolder }
    onViewHolderBound = { vh, _, it ->
        vh.messageText.text = it.text
        vh.sentAt.text = it.sentAt
    }
)
```
would become this:
Kotlin
```kt
register(
    type = Text::class.java
    layoutResource = R.layout.adapter_message_text_item
    viewHolder = { ::TextMessageViewHolder }
    onViewHolderBound = { vh, _, it ->
        vh.messageText.text = it.text
        vh.sentAt.text = it.sentAt
    }
)
```
With:
```kt
fun register(layoutResourceProvider: () -> Int) {
    // use layoutResourceProvider
}

fun register(layoutResource: Int) = register(
    layoutResourceProvider = { layoutResource }
)
```

**Comment by jobot0** [comment]
Hello! First thanks for the project. I've started using it on my new pet project :) Do you mind if I take this issue?

**Comment by ibrahimyilmaz** [comment]
Hello! Thank you for your contribution request. If you would take this issue, I really appreciate!

**Comment by ibrahimyilmaz** [comment]
Hello
@jobot0 I think this is done with https://github.com/ibrahimyilmaz/kiel/pull/39.
I hope that you havent started anything yet

**Comment by jobot0** [comment]
Hello @ibrahimyilmaz I was starting same direction so no problem :) Thanks again for the project and I'll try another issue at some point!
