### ISSUE TITLE
Add "import" information in README

### ISSUE THREAD

**Issue by cyb3rko** [ibrahimyilmaz/kiel#51]
Hi,
I just tried out your library and I have to say: **Awesome!**
I WILL use it in my projects from now on.

But it seems like `adapterOf` does not get imported automatically, so I had to search for the import in the sample app.
Maybe you should add the note to the README that you need the import `import me.ibrahimyilmaz.kiel.adapter.RecyclerViewAdapter.Companion.adapterOf` like in the [Download](https://github.com/ibrahimyilmaz/kiel#download) section.

Greetings!

**Comment by ibrahimyilmaz** [comment]
Hi @cyb3rko 

I am really glad to hear that.  Thank you for your feedback🙏🏻.

Next version, `adapterOf` function will be rescued from `me.ibrahimyilmaz.kiel.adapter.RecyclerViewAdapter.Companion`.

**Comment by cyb3rko** [comment]
Sorry, but what do you mean by

> ... `adapterOf` function will be rescued from `me.ibrahimyilmaz.kiel.adapter.RecyclerViewAdapter.Companion`.

??

**Comment by ibrahimyilmaz** [comment]
There will be `Adapters.kt`, which will contains `adapterOf` and `pageAdapterOf` methods. 
Just like `kotlin/collections/Collections.kt`.

**Comment by cyb3rko** [comment]
Oh ok, perfect!

**Comment by ibrahimyilmaz** [comment]
Hi @cyb3rko

`Adapters.kt` is ready in `v1.2.0`
