### ISSUE TITLE
[kiel] Support for load more functions

### ISSUE THREAD

**Issue by rainboy93** [ibrahimyilmaz/kiel#60]
Hi there,
RecyclerView usually have to handle a large amount of data, I think it really need to add support for load more functions.
What do you think?

**Comment by ibrahimyilmaz** [comment]
Hi @rainboy93,
Thank you for the issue. But could you elaborate the issue with example?

**Comment by rainboy93** [comment]
Hi @ibrahimyilmaz,
Just like Facebook or Instagram for example. We have many entities to get from server and we can not get it in one time.
If you could provide a delegate to trigger when we need to call API to get more data from server, it's really helpful.

**Comment by ibrahimyilmaz** [comment]
Hi @rainboy93,
Thanks for clarification, I think Google solves this with:

- https://developer.android.com/reference/android/arch/paging/PagedListAdapter
- https://developer.android.com/reference/kotlin/androidx/paging/PagingDataAdapter


Kiel has `PagingDataAdapter` builder at the moment and will have `PagedListAdapter` in v1.3.x. 

If you would like to create `PagedListAdapter`, your PR is welcome.

**Comment by rainboy93** [comment]
Hi @ibrahimyilmaz ,
Thank you! I will take a look asap.
