### ISSUE TITLE
[kiel] Drop Jetifier

### ISSUE THREAD

**Issue by raquezha** [ibrahimyilmaz/kiel#67]
### **FEATURE REQUEST**
Hi! Thank you for making Kiel! I've played with it for some time now and I want to use it in our project but this issue is we are trying to reduce build time by **_dropping jetifier_**.

We found out by dropping jetifier we can reduce a significant amount of build time. thank you!

### **Describe the solution you'd like**
I've forked your project and dropped jetifier, test it and it works! I just disabled the app module because of some conflicts. Anyway it's working fine in my test project. 

```
 implementation 'com.github.raquezha:kiel:1.2.1-beta'
```

### **Describe alternatives you've considered**
I hope you consider this feature request

### **Additional context**
1. Adam Bennet's Article about droping jetifier: https://adambennett.dev/2020/08/disabling-jetifier/
1. Can I Drop Jetifier Repo: https://github.com/plnice/can-i-drop-jetifier

**Comment by ibrahimyilmaz** [comment]
Hi @raquezha 
Firstly thank you for such a great feedback.
PRs are welcome =) Please open PR and we make it happen!

Sincerely
Ibrahim

**Comment by ibrahimyilmaz** [comment]
- I have integrated `CanIDropJetifier` and checked it.

- when we remove `implementation "com.github.florent37:glidepalette:$versions.glidePaletteVersion"`, everything is fine. I just simply removed and everything seems to be working well.

As you give the idea, I would be glad to get PR from you(Also your contribution will be visible in the repo).

If you plan to do it, please consider to change Check Step in Github Actions. 

```bash
    - name: Check
        run: ./gradlew -Pandroid.enableJetifier=false canIDropJetifier check
```
Sincerely
Ibrahim

**Comment by raquezha** [comment]
My solution is to exclude appcompat support when importing glidepalette @ibrahimyilmaz hehe I'll submit a PR

**Comment by raquezha** [comment]
Thank you so much :)
