### ISSUE TITLE
Publish to Maven Central 

### ISSUE THREAD

**Issue by arosca-nl** [ibrahimyilmaz/kiel#72]
https://blog.gradle.org/jcenter-shutdown

**Comment by ibrahimyilmaz** [comment]
Hi @arosca-nl ,
I will open 2-3 small PRs for that(if you also review it, I will appreciate)

**Comment by ibrahimyilmaz** [comment]
I have started the publishing process https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/
Now waiting for result of this https://issues.sonatype.org/browse/OSSRH-67874

**Comment by ibrahimyilmaz** [comment]
Upload is done. I will integrate it to pipeline and update the readme.
[
![Screen Shot 2021-04-27 at 10 00 56 PM](https://user-images.githubusercontent.com/734592/116305446-155fb100-a7a4-11eb-8568-bea733293e1e.png)
](url)

**Comment by ibrahimyilmaz** [comment]
Kiel uploaded to MavenCentral. Usage is updated with this PR.

https://github.com/ibrahimyilmaz/kiel/pull/74

**Comment by ibrahimyilmaz** [comment]
kiel 1.3.0 version will be uploaded to the server via our pipeline. After than this issue will be closed. 
Thanks for your interest and support @arosca-nl.

https://github.com/ibrahimyilmaz/kiel/pull/75
